### PR TITLE
Bump telegram-web-apps.js

### PR DESCRIPTION
**Pull request by SaeedPoureshghi**
Bump telegram-web-apps.js version to include new features

### CODE REVIEW

**Comment by emargin** [comment]
@ArthurStam

**Comment by AvetikNersisyan** [comment]
Why this is not approved?

**Comment by Witcher1337** [comment]
Release it ASAP please

**Review by meh7an — APPROVED** [review]

**Comment by ArthurStam** [comment]
Sorry, folks, I was out of office. I will update version of types and sdk today. This MR updates only JS file, which is wrong.

**Pull request closed without merging**
